[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "qualiframe"
version = "0.1.0"
description = "A lightweight data quality auditing tool"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "matplotlib",
    "seaborn",
    "reportlab"
]

[tool.setuptools.packages.find]
include = ["qualiframe*"]