[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "qualiframe"
version = "0.1.1"
description = "Automated data quality and statistical reporting for pandas DataFrames"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    {name = "Heshva"}
]

dependencies = [
    "pandas",
    "matplotlib",
    "seaborn",
    "reportlab"
]

[tool.setuptools.packages.find]
include = ["qualiframe*"]